version: '3.8'
services:
  frontend:
    build:
      context: ./react/app
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./react/app
        target: /usr/src/app
    depends_on:
      - backend
    networks:
      - backend

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodb-data:
