stages:
  - test
  - build
  - deploy

test_backend:
  stage: test
  image: node:latest
  script:
    - cd bcend
    - npm install
    - npm test

test_frontend:
  stage: test
  image: node:latest
  script:
    - cd react/app
    - npm install
    - npm test

build:
  stage: build
  image: node:latest
  script:
    - cd react/app
    - npm install
    - npm run build
  artifacts:
    paths:
      - react/app/build

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # will be implemented later
  only:
    - main
