version: '3'
services:
  mongodb:
    image: techblog/mongodb
    ports:
      - '27017:27017'
    networks:
      - app-network

  app:
    image: techblog
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
