name: NodeJS with Webpack

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: frontend/src

      - name: Build
        run: npm run build
        working-directory: frontend/src

      - name: List files in dist directory
        run: ls -la dist/
        working-directory: frontend/src

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: webpack-artifacts
          path: frontend/src/dist/
